### ISSUE TITLE
Git push causes "Error: 422 Unprocessable Entity"

### ISSUE THREAD

**Issue by Shaxine** [chazeon/olgitbridge#1]
Hello,

I'm using Overleaft CE with docker (sharelatex/sharelatex:with-texlive-full).
I could git clone and pull successfully. But when doing a git push after committing file changes, the git client reports a successful push, but the bridge reports the following error:

```
 [4] getting request for 657f8624ee62673766e3d90d
 [4] requesting user semaphore
 [3] upsyncing
 [3] overleaf joining project
 [3] io connect to 657f8624ee62673766e3d90d
 [3] iosocket disconnect
 [3] upsyncing ./
 [3] uploading ./cover.tex
 /var/olgitbridge/src/olops/upload.js:21
 		throw new Error( e.response.status + ' ' + e.response.statusText );
 		      ^
 
 Error: 422 Unprocessable Entity
     at module.exports [as upload] (/var/olgitbridge/src/olops/upload.js:21:9)
     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
     at async upload (/var/olgitbridge/src/upsync.js:42:2)
     at async upSyncDir (/var/olgitbridge/src/upsync.js:108:5)
     at async module.exports (/var/olgitbridge/src/upsync.js:143:2)
     at async endRemoteGitRequest (/var/olgitbridge/src/server.js:77:3)
```

**Comment by chazeon** [comment]
How did you start the olgitbridge? Using docker or locally? I remember the project config `config.js` is not very clever on path concatenation and might sometimes fail.

**Comment by chazeon** [comment]
Which version of overleaf are you using?

**Comment by Shaxine** [comment]
Thanks for the quick response.

I use olgitbridge through docker and changed `config.olServer = 'http://overleaf';` and `config.baseDir = '/var/olgitbridge/data/';` in `config.js` to match the OL container name and the bridge volume data.

I forgot that I changed the container tag after following https://github.com/overleaf/overleaf/wiki/Quick-Start-Guide#latex-environment based of `sharelatex/sharelatex` I'm having a hard time finding the OL version...

**Comment by Shaxine** [comment]
It's safe to say the version is > 4.0 . Just don't know where to look for the running version.

**Comment by Shaxine** [comment]
Should I provide any additional information?

**Comment by chazeon** [comment]
Sorry I am a little busy recently and have not got time to really dig into this yet.
